<?php
/*
Plugin Name: Terttus Product Manager
Description: Moderne produktstyring oven på WooCommerce.
Version: 1.0.0
Author: Terttus
Requires PHP: 7.4
*/
if(!defined('ABSPATH'))exit;
define('TPM_VERSION','1.0.0');
function tpm_menu(){add_submenu_page('woocommerce','Terttus Product Manager','Produkt Manager','edit_products','terttus-product-manager','tpm_screen');}add_action('admin_menu','tpm_menu',30);
function tpm_assets($h){if(strpos($h,'terttus-product-manager')===false)return;wp_enqueue_media();wp_enqueue_style('tpm',plugins_url('assets/admin.css',__FILE__),[],TPM_VERSION);wp_enqueue_script('tpm',plugins_url('assets/admin.js',__FILE__),['jquery'],TPM_VERSION,true);}add_action('admin_enqueue_scripts','tpm_assets');
function tpm_val($p,$k,$d=''){if(!$p)return $d;if(in_array($k,['ean','brand','cost','supplier','supplier_sku','supplier_url'],true))return get_post_meta($p->get_id(),'_tpm_'.$k,true);$m=['name'=>'get_name','sku'=>'get_sku','price'=>'get_regular_price','sale'=>'get_sale_price','stock'=>'get_stock_quantity','stock_status'=>'get_stock_status','short_description'=>'get_short_description','description'=>'get_description','image'=>'get_image_id'];return isset($m[$k])?$p->{$m[$k]}():$d;}
function tpm_screen(){
 if(!class_exists('WooCommerce')){echo'<div class="notice notice-error"><p>WooCommerce skal være aktivt.</p></div>';return;}
 $id=absint($_GET['product_id']??0);$p=$id?wc_get_product($id):null;if($id&&!$p)wp_die('Produktet blev ikke fundet.');
 if(isset($_GET['saved']))echo'<div class="notice notice-success is-dismissible"><p>Produktet er gemt.</p></div>';
 $cats=get_terms(['taxonomy'=>'product_cat','hide_empty'=>false]);$selected=$p?$p->get_category_ids():[];$gallery=$p?$p->get_gallery_image_ids():[];
 ?><div class="wrap tpm"><div class="tpm-head"><div><h1><?php echo $p?'Redigér produkt':'Nyt produkt';?></h1><p>En enkel arbejdsgang, gemt direkte i WooCommerce.</p></div><div class="tpm-head-actions"><a class="button" href="<?php echo esc_url(admin_url('edit.php?post_type=product'));?>">Alle produkter</a><?php if($p):?><a class="button" href="<?php echo esc_url(get_permalink($p->get_id()));?>" target="_blank">Se produkt</a><?php endif;?><span class="tpm-badge">Terttus</span></div></div>
 <form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('tpm_save');?><input type="hidden" name="action" value="tpm_save_product"><input type="hidden" name="product_id" value="<?php echo $id;?>">
 <div class="tpm-layout"><main>
 <section class="tpm-card"><h2>1. Grundinfo</h2><div class="tpm-grid"><label class="wide">Produktnavn<input required name="name" value="<?php echo esc_attr(tpm_val($p,'name'));?>"></label><label>SKU / varenummer<input name="sku" value="<?php echo esc_attr(tpm_val($p,'sku'));?>"></label><label>EAN / GTIN<input name="ean" value="<?php echo esc_attr(tpm_val($p,'ean'));?>"></label><label>Mærke<input name="brand" value="<?php echo esc_attr(tpm_val($p,'brand'));?>"></label><label>Kategori<select name="category"><option value="">Vælg kategori</option><?php foreach($cats as$c)echo'<option value="'.intval($c->term_id).'" '.selected(in_array($c->term_id,$selected),true,false).'>'.esc_html($c->name).'</option>';?></select></label></div></section>
 <section class="tpm-card"><h2>2. Billeder</h2><input type="hidden" id="tpm-image-id" name="image_id" value="<?php echo intval(tpm_val($p,'image'));?>"><input type="hidden" id="tpm-gallery-ids" name="gallery_ids" value="<?php echo esc_attr(implode(',',$gallery));?>"><div class="tpm-media"><div id="tpm-main-preview" class="tpm-image-preview"><?php if(tpm_val($p,'image'))echo wp_get_attachment_image(tpm_val($p,'image'),'medium');?></div><div><button type="button" class="button tpm-pick-main">Vælg hovedbillede</button><button type="button" class="button tpm-pick-gallery">Vælg galleri</button><p class="description">Bruger WordPress' eget mediebibliotek.</p></div></div><div id="tpm-gallery-preview" class="tpm-gallery"><?php foreach($gallery as$g)echo wp_get_attachment_image($g,'thumbnail');?></div></section>
 <section class="tpm-card"><h2>3. Pris & avance</h2><div class="tpm-grid"><label>Indkøbspris ekskl. moms<input type="number" step=".01" min="0" name="cost" id="tpm-cost" value="<?php echo esc_attr(tpm_val($p,'cost'));?>"></label><label>Salgspris inkl. moms<input required type="number" step=".01" min="0" name="price" id="tpm-price" value="<?php echo esc_attr(tpm_val($p,'price'));?>"></label><label>Tilbudspris<input type="number" step=".01" min="0" name="sale" value="<?php echo esc_attr(tpm_val($p,'sale'));?>"></label><div class="tpm-metric"><span>Estimeret avance</span><strong id="tpm-margin">—</strong></div></div></section>
 <section class="tpm-card"><h2>4. Lager & leverandør</h2><div class="tpm-grid"><label>Lagerstatus<select name="stock_status"><?php foreach(['instock'=>'På lager','onbackorder'=>'Bestillingsvare','outofstock'=>'Udsolgt']as$v=>$l)echo'<option value="'.$v.'" '.selected(tpm_val($p,'stock_status','instock'),$v,false).'>'.$l.'</option>';?></select></label><label>Antal på lager<input type="number" min="0" name="stock" value="<?php echo esc_attr(tpm_val($p,'stock'));?>"></label><label>Leverandør<input name="supplier" value="<?php echo esc_attr(tpm_val($p,'supplier'));?>" placeholder="fx DCS"></label><label>Leverandørvarenr.<input name="supplier_sku" value="<?php echo esc_attr(tpm_val($p,'supplier_sku'));?>"></label><label class="wide">Leverandør-URL<input type="url" name="supplier_url" value="<?php echo esc_attr(tpm_val($p,'supplier_url'));?>"></label></div></section>
 <section class="tpm-card"><h2>5. Beskrivelse</h2><label>Kort salgstekst<textarea name="short_description" rows="4"><?php echo esc_textarea(tpm_val($p,'short_description'));?></textarea></label><label>Lang beskrivelse<textarea name="description" rows="9"><?php echo esc_textarea(tpm_val($p,'description'));?></textarea></label></section>
 <section class="tpm-card"><h2>6. Specifikationer</h2><div id="tpm-specs"><?php $specs=$p?get_post_meta($p->get_id(),'_tpm_specs',true):[];if(!is_array($specs))$specs=[];foreach($specs as$s):?><div class="tpm-spec"><input name="spec_name[]" value="<?php echo esc_attr($s['name']);?>" placeholder="Egenskab"><input name="spec_value[]" value="<?php echo esc_attr($s['value']);?>" placeholder="Værdi"><button type="button" class="button tpm-remove-spec">×</button></div><?php endforeach;?></div><button type="button" class="button tpm-add-spec">+ Tilføj specifikation</button></section>
 </main><aside><section class="tpm-card tpm-sticky"><h2>Publicering</h2><label>Status<select name="status"><option value="draft" <?php selected($p?$p->get_status():'draft','draft');?>>Kladde</option><option value="publish" <?php selected($p?$p->get_status():'draft','publish');?>>Udgivet</option></select></label><button class="button button-primary button-hero tpm-save">Gem produkt</button><?php if($p):?><a class="button tpm-duplicate" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=tpm_duplicate_product&product_id='.$p->get_id()),'tpm_duplicate_'.$p->get_id()));?>">Duplikér produkt</a><?php endif;?><div class="tpm-check"><strong>Produkt-tjek</strong><ul id="tpm-checklist"><li data-check="name">Produktnavn</li><li data-check="price">Pris</li><li data-check="image">Hovedbillede</li><li data-check="category">Kategori</li></ul></div></section></aside></div></form></div><?php
}
function tpm_save_product(){if(!current_user_can('edit_products')||!check_admin_referer('tpm_save'))wp_die('Ingen adgang.');$id=absint($_POST['product_id']??0);$p=$id?wc_get_product($id):new WC_Product_Simple();if(!$p)wp_die('Produkt ikke fundet.');$name=sanitize_text_field($_POST['name']??'');if(!$name)wp_die('Produktnavn mangler.');$p->set_name($name);$p->set_status(in_array($_POST['status']??'draft',['draft','publish'],true)?$_POST['status']:'draft');$p->set_sku(sanitize_text_field($_POST['sku']??''));$p->set_regular_price(wc_format_decimal($_POST['price']??''));$sale=wc_format_decimal($_POST['sale']??'');$p->set_sale_price($sale);$p->set_short_description(wp_kses_post($_POST['short_description']??''));$p->set_description(wp_kses_post($_POST['description']??''));$p->set_stock_status(in_array($_POST['stock_status']??'instock',['instock','outofstock','onbackorder'],true)?$_POST['stock_status']:'instock');if(($_POST['stock']??'')!==''){$p->set_manage_stock(true);$p->set_stock_quantity(max(0,intval($_POST['stock'])));}else{$p->set_manage_stock(false);}$cat=absint($_POST['category']??0);$p->set_category_ids($cat?[$cat]:[]);$p->set_image_id(absint($_POST['image_id']??0));$gallery=array_filter(array_map('absint',explode(',',sanitize_text_field($_POST['gallery_ids']??''))));$p->set_gallery_image_ids($gallery);$id=$p->save();foreach(['ean','brand','cost','supplier','supplier_sku','supplier_url']as$k)update_post_meta($id,'_tpm_'.$k,sanitize_text_field($_POST[$k]??''));$names=(array)($_POST['spec_name']??[]);$vals=(array)($_POST['spec_value']??[]);$specs=[];foreach($names as$i=>$n){$n=sanitize_text_field($n);$v=sanitize_text_field($vals[$i]??'');if($n||$v)$specs[]=['name'=>$n,'value'=>$v];}update_post_meta($id,'_tpm_specs',$specs);wp_safe_redirect(add_query_arg(['page'=>'terttus-product-manager','saved'=>1,'product_id'=>$id],admin_url('admin.php')));exit;}add_action('admin_post_tpm_save_product','tpm_save_product');
function tpm_duplicate(){if(!current_user_can('edit_products'))wp_die('Ingen adgang.');$id=absint($_GET['product_id']??0);check_admin_referer('tpm_duplicate_'.$id);$src=wc_get_product($id);if(!$src)wp_die('Produkt ikke fundet.');$copy=clone $src;$copy->set_id(0);$copy->set_name($src->get_name().' – kopi');$copy->set_status('draft');$copy->set_sku('');$new=$copy->save();foreach(['ean','brand','cost','supplier','supplier_sku','supplier_url','specs']as$k){$v=get_post_meta($id,'_tpm_'.$k,true);if($v!=='')update_post_meta($new,'_tpm_'.$k,$v);}wp_safe_redirect(add_query_arg(['page'=>'terttus-product-manager','product_id'=>$new],admin_url('admin.php')));exit;}add_action('admin_post_tpm_duplicate_product','tpm_duplicate');
